### ISSUE TITLE
no more apm_linux/lib ???

### ISSUE THREAD

**Issue by haolee21** [APMonitor/apm_server#2]
On your website https://apmonitor.com/wiki/index.php/Main/APMonitorServerLinux
There is a 
``` 
sudo cp -n apm_linux/lib/* /usr/lib/
```
However, I don't think there is a lib folder in this repository, is this step no longer required?

**Comment by APMonitor** [comment]
That is correct. The lib folder is only needed if you have a version that runs IPOPT locally. The current version of the binary apm does not need the lib directory.
